# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPessoa',
            fields=[
                ('pes_matricula', models.IntegerField(primary_key=True, serialize=False)),
                ('pes_nome', models.CharField(max_length=500)),
                ('set_id', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Pessoas',
                'db_table': 'v_pessoa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VSetor',
            fields=[
                ('set_id', models.IntegerField(primary_key=True, serialize=False)),
                ('set_nome', models.CharField(max_length=500)),
                ('set_sigla', models.CharField(max_length=100)),
                ('set_id_superior', models.IntegerField(blank=True, null=True)),
                ('set_ativo', models.IntegerField()),
                ('set_tipo', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Setores',
                'db_table': 'v_setor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ramal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=200)),
                ('pessoa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.VPessoa')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.VSetor')),
            ],
        ),
    ]
