# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_ramal_vpessoa_vsetor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramal',
            name='pessoa',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.VPessoa'),
        ),
        migrations.AlterField(
            model_name='ramal',
            name='setor',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cadastro.VSetor'),
        ),
    ]
